language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
  - TWIG_VERSION="^1.0"
  - TWIG_VERSION="^2.0"

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    exclude:
        - php: 5.3
          env: TWIG_VERSION="^2.0"
        - php: 5.4
          env: TWIG_VERSION="^2.0"
        - php: 5.5
          env: TWIG_VERSION="^2.0"
        - php: 5.6
          env: TWIG_VERSION="^2.0"
        - php: hhvm
          env: TWIG_VERSION="^2.0"

install: composer require twig/twig:${TWIG_VERSION}

script: phpunit
